server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?userUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/shanghai
    username: root
    password: 12345678
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: zys.store.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
user:
  address:
    max-count: 20


